#!/bin/bash
#
# <daemonname> <summary>
#
# chkconfig:   <default runlevel(s)> <start> <stop>
# description: <description, split multiple lines with \
#              a backslash>

### BEGIN INIT INFO
# Provides:
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:
# Default-Stop:
# Short-Description:
# Description:
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

LSYNCD_ROOT=${LSYNCD_ROOT:-$(pwd)}

exec="${LSYNCD_ROOT}/bin/lsyncd"
prog=$(basename "$0")
config="${LSYNCD_ROOT}/etc/lsyncd/${prog}.lua"

#[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

pidfile="${LSYNCD_ROOT}/var/run/${prog}.pid"
logfile="${LSYNCD_ROOT}/var/log/${prog}.log"
#lockfile=/var/lock/subsys/$prog
start="$exec -pidfile $pidfile -logfile $logfile $config"

start() {
    [ -x "$exec" ] || exit 5
    [ -f "$config" ] || exit 6
    echo -n $"Starting $prog: "
    # if not running, start it up here, usually something like "daemon $exec"
    daemon --pidfile="${pidfile}" "$start"
    retval=$?
    echo
    [ $retval -eq 0 ] #&& touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    # stop it here, often "killproc $prog"
    killproc -p "$pidfile" "$prog"
    retval=$?
    echo
    [ $retval -eq 0 ] #&& rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -p "$pidfile" "$prog"
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
